/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Code;

import java.awt.Color;
import Code.AdmScreen;
import java.sql.*;
import Auxiliar.SQL.Updates;

/**
 *
 * @author Alunos
 */
public class Adm2Screen extends javax.swing.JFrame {
    
    Statement stmt;
    ResultSet rs;
    
    Connection conn;
    String user = "root", password = "1234", host = "jdbc:mysql://127.0.0.1:4890/aps3";
    
    Updates update = new Updates();
    
    /**
     * Creates new form Adm2Screen
     */
    public Adm2Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgBox = new javax.swing.JPanel();
        bodyBox = new javax.swing.JPanel();
        protocoloTxt = new javax.swing.JLabel();
        protocoloNumTxt = new javax.swing.JLabel();
        userTxt = new javax.swing.JLabel();
        cpfTxt = new javax.swing.JLabel();
        dataTxt = new javax.swing.JLabel();
        tipTxt1 = new javax.swing.JLabel();
        tipo2Txt1 = new javax.swing.JLabel();
        textBox = new javax.swing.JPanel();
        userTextTxt = new javax.swing.JLabel();
        LiberarBttn = new javax.swing.JButton();
        liberarDeposito = new javax.swing.JCheckBox();
        liberarExtrato = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        BgBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodyBox.setBackground(new java.awt.Color(6, 8, 66));
        bodyBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        protocoloTxt.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        protocoloTxt.setText("Protocolo");
        bodyBox.add(protocoloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        protocoloNumTxt.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        protocoloNumTxt.setText("Num");
        bodyBox.add(protocoloNumTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        userTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userTxt.setText("POR:");
        bodyBox.add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        cpfTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cpfTxt.setText("CPF");
        bodyBox.add(cpfTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        dataTxt.setText("03/10/2058");
        bodyBox.add(dataTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        tipTxt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tipTxt1.setText("TIPO:");
        bodyBox.add(tipTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        tipo2Txt1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipo2Txt1.setText("tipo");
        bodyBox.add(tipo2Txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        textBox.setBackground(new java.awt.Color(4, 5, 43));
        textBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));

        userTextTxt.setText("pedido do usuario");

        javax.swing.GroupLayout textBoxLayout = new javax.swing.GroupLayout(textBox);
        textBox.setLayout(textBoxLayout);
        textBoxLayout.setHorizontalGroup(
            textBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userTextTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
        textBoxLayout.setVerticalGroup(
            textBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(textBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userTextTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        bodyBox.add(textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 280, 270));

        LiberarBttn.setBackground(new java.awt.Color(14, 0, 35));
        LiberarBttn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LiberarBttn.setForeground(new java.awt.Color(255, 255, 51));
        LiberarBttn.setText("Liberar");
        LiberarBttn.setToolTipText("");
        LiberarBttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        LiberarBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LiberarBttnMouseClicked(evt);
            }
        });
        LiberarBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiberarBttnActionPerformed(evt);
            }
        });
        bodyBox.add(LiberarBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 90, 40));

        liberarDeposito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        liberarDeposito.setText("Depósito");
        liberarDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liberarDepositoMouseClicked(evt);
            }
        });
        liberarDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberarDepositoActionPerformed(evt);
            }
        });
        bodyBox.add(liberarDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        liberarExtrato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        liberarExtrato.setText("Extrato");
        liberarExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liberarExtratoActionPerformed(evt);
            }
        });
        bodyBox.add(liberarExtrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, -1, -1));

        BgBox.add(bodyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 340, 700));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bg.png"))); // NOI18N
        BgBox.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(BgBox);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean deposit, extract;
    
    public boolean getDeposit(){
        return this.deposit;
    }
    
    public boolean getExtract(){
        return this.extract;
    }
    
    public void setDeposit(boolean deposit){
        this.deposit = deposit;
    }
    
    public void setExtract(boolean extract){
        this.extract = extract;
    }
    
    private void LiberarBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiberarBttnActionPerformed
    }//GEN-LAST:event_LiberarBttnActionPerformed

    private void LiberarBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LiberarBttnMouseClicked
        AdmScreen adm = new AdmScreen();
        this.setVisible(false);
        adm.setVisible(true);
        String check, check2;
        
        if (getExtract() == true){
           check = "1";
        }
        else{
            check = "0";
        }
        
        if (getDeposit() == true){
           check2 = "1";
        }
        else{
            check2 = "0";
        }
        int protocolo = Integer.parseInt(protocoloNumTxt.getText());
        update.updateSQLExtrato(check, protocolo);
        update.updateSQLDeposito(check2, protocolo);
    }//GEN-LAST:event_LiberarBttnMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cpfTxt.setForeground(Color.white);
        dataTxt.setForeground(Color.white);
        jLabel2.setForeground(Color.white);
        protocoloNumTxt.setForeground(Color.white);
        protocoloTxt.setForeground(Color.white);
        tipTxt1.setForeground(Color.white);
        tipo2Txt1.setForeground(Color.white);
        userTextTxt.setForeground(Color.white);
        userTxt.setForeground(Color.white);
        liberarDeposito.setForeground(Color.white);
        liberarExtrato.setForeground(Color.white);
        
        AdmScreen adm = new AdmScreen();
        
        String i = Integer.toString(adm.i);
        
        try{
            conn = DriverManager.getConnection(host, user, password);
            stmt = conn.createStatement();
            
            rs = stmt.executeQuery("SELECT * FROM protocolo");
            
            while (rs.next()){
                if (rs.getString("id").equals(i)){
                    protocoloNumTxt.setText(rs.getString("id_protocolo"));
                    dataTxt.setText(rs.getString("data"));
                    tipo2Txt1.setText(rs.getString("tipo"));
                    cpfTxt.setText(rs.getString("cpf_cliente"));
                    userTextTxt.setText(rs.getString("historico"));
                }
            }
        } catch (SQLException e){
            throw new IllegalStateException("Erro!", e);
        }
        //protocoloNumTxt.setText(adm.newProto[i]);
        //dataTxt.setText(adm.newData[i]);
        //tipo2Txt1.setText(adm.newTipo[i]);
        //cpfTxt.setText(adm.newCpf[i]);
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void liberarExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberarExtratoActionPerformed
       setExtract(liberarExtrato.isSelected());
    }//GEN-LAST:event_liberarExtratoActionPerformed

    private void liberarDepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liberarDepositoMouseClicked

    }//GEN-LAST:event_liberarDepositoMouseClicked

    private void liberarDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liberarDepositoActionPerformed
         setDeposit(liberarDeposito.isSelected());
    }//GEN-LAST:event_liberarDepositoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adm2Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adm2Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adm2Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adm2Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adm2Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgBox;
    private javax.swing.JButton LiberarBttn;
    private javax.swing.JPanel bodyBox;
    private javax.swing.JLabel cpfTxt;
    private javax.swing.JLabel dataTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox liberarDeposito;
    private javax.swing.JCheckBox liberarExtrato;
    private javax.swing.JLabel protocoloNumTxt;
    private javax.swing.JLabel protocoloTxt;
    private javax.swing.JPanel textBox;
    private javax.swing.JLabel tipTxt1;
    private javax.swing.JLabel tipo2Txt1;
    private javax.swing.JLabel userTextTxt;
    private javax.swing.JLabel userTxt;
    // End of variables declaration//GEN-END:variables
}
