/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Code;

import javax.swing.JLabel;
import javax.swing.JPanel;
import java.sql.*;

/**
 *
 * @author Alunos
 */
public class AdmScreen extends javax.swing.JFrame {
    Statement stmt;
    ResultSet rs;
    
    Connection conn;
    String user = "root", password = "1234", host = "jdbc:mysql://127.0.0.1:4890/aps3";
    
    Adm2Screen adm2 = new Adm2Screen();
    
    
    
    /**
     * Creates new form AdmScreen
     */
    public AdmScreen() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgBox = new javax.swing.JPanel();
        bodyBox = new javax.swing.JPanel();
        roll1Box = new javax.swing.JPanel();
        protocoloTxt = new javax.swing.JLabel();
        cpfTxt = new javax.swing.JLabel();
        tipoTxt = new javax.swing.JLabel();
        dataTxt = new javax.swing.JLabel();
        ColumnTxt = new javax.swing.JLabel();
        ColumnTxt1 = new javax.swing.JLabel();
        ColumnTxt2 = new javax.swing.JLabel();
        roll1Box1 = new javax.swing.JPanel();
        protocoloTxt1 = new javax.swing.JLabel();
        cpfTxt1 = new javax.swing.JLabel();
        tipoTxt1 = new javax.swing.JLabel();
        dataTxt1 = new javax.swing.JLabel();
        ColumnTxt3 = new javax.swing.JLabel();
        ColumnTxt4 = new javax.swing.JLabel();
        ColumnTxt5 = new javax.swing.JLabel();
        roll1Box2 = new javax.swing.JPanel();
        protocoloTxt2 = new javax.swing.JLabel();
        cpfTxt2 = new javax.swing.JLabel();
        tipoTxt2 = new javax.swing.JLabel();
        dataTxt2 = new javax.swing.JLabel();
        ColumnTxt6 = new javax.swing.JLabel();
        ColumnTxt7 = new javax.swing.JLabel();
        ColumnTxt8 = new javax.swing.JLabel();
        roll1Box3 = new javax.swing.JPanel();
        protocoloTxt3 = new javax.swing.JLabel();
        cpfTxt3 = new javax.swing.JLabel();
        tipoTxt3 = new javax.swing.JLabel();
        dataTxt3 = new javax.swing.JLabel();
        ColumnTxt9 = new javax.swing.JLabel();
        ColumnTxt10 = new javax.swing.JLabel();
        ColumnTxt11 = new javax.swing.JLabel();
        roll1Box4 = new javax.swing.JPanel();
        protocoloTxt4 = new javax.swing.JLabel();
        cpfTxt4 = new javax.swing.JLabel();
        tipoTxt4 = new javax.swing.JLabel();
        dataTxt4 = new javax.swing.JLabel();
        ColumnTxt12 = new javax.swing.JLabel();
        ColumnTxt13 = new javax.swing.JLabel();
        ColumnTxt14 = new javax.swing.JLabel();
        roll1Box5 = new javax.swing.JPanel();
        protocoloTxt5 = new javax.swing.JLabel();
        cpfTxt5 = new javax.swing.JLabel();
        tipoTxt5 = new javax.swing.JLabel();
        dataTxt5 = new javax.swing.JLabel();
        ColumnTxt15 = new javax.swing.JLabel();
        ColumnTxt16 = new javax.swing.JLabel();
        ColumnTxt17 = new javax.swing.JLabel();
        roll1Box6 = new javax.swing.JPanel();
        protocoloTxt6 = new javax.swing.JLabel();
        cpfTxt6 = new javax.swing.JLabel();
        tipoTxt6 = new javax.swing.JLabel();
        dataTxt6 = new javax.swing.JLabel();
        ColumnTxt18 = new javax.swing.JLabel();
        ColumnTxt19 = new javax.swing.JLabel();
        ColumnTxt20 = new javax.swing.JLabel();
        roll1Box7 = new javax.swing.JPanel();
        protocoloTxt7 = new javax.swing.JLabel();
        cpfTxt7 = new javax.swing.JLabel();
        tipoTxt7 = new javax.swing.JLabel();
        dataTxt7 = new javax.swing.JLabel();
        ColumnTxt21 = new javax.swing.JLabel();
        ColumnTxt22 = new javax.swing.JLabel();
        ColumnTxt23 = new javax.swing.JLabel();
        roll1Box8 = new javax.swing.JPanel();
        protocoloTxt8 = new javax.swing.JLabel();
        cpfTxt8 = new javax.swing.JLabel();
        tipoTxt8 = new javax.swing.JLabel();
        dataTxt8 = new javax.swing.JLabel();
        ColumnTxt24 = new javax.swing.JLabel();
        ColumnTxt25 = new javax.swing.JLabel();
        ColumnTxt26 = new javax.swing.JLabel();
        roll1Box9 = new javax.swing.JPanel();
        protocoloTxt9 = new javax.swing.JLabel();
        cpfTxt9 = new javax.swing.JLabel();
        tipoTxt9 = new javax.swing.JLabel();
        dataTxt9 = new javax.swing.JLabel();
        ColumnTxt27 = new javax.swing.JLabel();
        ColumnTxt28 = new javax.swing.JLabel();
        ColumnTxt29 = new javax.swing.JLabel();
        roll1Box10 = new javax.swing.JPanel();
        protocoloTxt10 = new javax.swing.JLabel();
        cpfTxt10 = new javax.swing.JLabel();
        tipoTxt10 = new javax.swing.JLabel();
        dataTxt10 = new javax.swing.JLabel();
        ColumnTxt30 = new javax.swing.JLabel();
        ColumnTxt31 = new javax.swing.JLabel();
        ColumnTxt32 = new javax.swing.JLabel();
        roll1Box11 = new javax.swing.JPanel();
        protocoloTxt11 = new javax.swing.JLabel();
        cpfTxt11 = new javax.swing.JLabel();
        tipoTxt11 = new javax.swing.JLabel();
        dataTxt11 = new javax.swing.JLabel();
        ColumnTxt33 = new javax.swing.JLabel();
        ColumnTxt34 = new javax.swing.JLabel();
        ColumnTxt35 = new javax.swing.JLabel();
        roll1Box12 = new javax.swing.JPanel();
        protocoloTxt12 = new javax.swing.JLabel();
        cpfTxt12 = new javax.swing.JLabel();
        tipoTxt12 = new javax.swing.JLabel();
        dataTxt12 = new javax.swing.JLabel();
        ColumnTxt36 = new javax.swing.JLabel();
        ColumnTxt37 = new javax.swing.JLabel();
        ColumnTxt38 = new javax.swing.JLabel();
        roll1Box13 = new javax.swing.JPanel();
        protocoloTxt13 = new javax.swing.JLabel();
        cpfTxt13 = new javax.swing.JLabel();
        tipoTxt13 = new javax.swing.JLabel();
        dataTxt13 = new javax.swing.JLabel();
        ColumnTxt39 = new javax.swing.JLabel();
        ColumnTxt40 = new javax.swing.JLabel();
        ColumnTxt41 = new javax.swing.JLabel();
        roll1Box14 = new javax.swing.JPanel();
        protocoloTxt14 = new javax.swing.JLabel();
        cpfTxt14 = new javax.swing.JLabel();
        tipoTxt14 = new javax.swing.JLabel();
        dataTxt14 = new javax.swing.JLabel();
        ColumnTxt42 = new javax.swing.JLabel();
        ColumnTxt43 = new javax.swing.JLabel();
        ColumnTxt44 = new javax.swing.JLabel();
        roll1Box15 = new javax.swing.JPanel();
        protocoloTxt15 = new javax.swing.JLabel();
        cpfTxt15 = new javax.swing.JLabel();
        tipoTxt15 = new javax.swing.JLabel();
        dataTxt15 = new javax.swing.JLabel();
        ColumnTxt45 = new javax.swing.JLabel();
        ColumnTxt46 = new javax.swing.JLabel();
        ColumnTxt47 = new javax.swing.JLabel();
        footerBox = new javax.swing.JPanel();
        squareTxt = new javax.swing.JLabel();
        ballTxt = new javax.swing.JLabel();
        backTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        bodyBox.setBackground(new java.awt.Color(6, 8, 66));
        bodyBox.setMaximumSize(new java.awt.Dimension(361, 763));
        bodyBox.setMinimumSize(new java.awt.Dimension(361, 763));
        bodyBox.setPreferredSize(new java.awt.Dimension(361, 763));
        bodyBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roll1Box.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box.setToolTipText("");
        roll1Box.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1BoxMouseClicked(evt);
            }
        });

        protocoloTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt.setText("IdProtocolo");

        cpfTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt.setText("CPF");

        tipoTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt.setText("tipo");

        dataTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt.setText("data");

        ColumnTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt.setText("|");

        ColumnTxt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt1.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt1.setText("|");

        ColumnTxt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt2.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt2.setText("|");

        javax.swing.GroupLayout roll1BoxLayout = new javax.swing.GroupLayout(roll1Box);
        roll1Box.setLayout(roll1BoxLayout);
        roll1BoxLayout.setHorizontalGroup(
            roll1BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1BoxLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt)
                .addGap(16, 16, 16))
        );
        roll1BoxLayout.setVerticalGroup(
            roll1BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1BoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt)
                    .addComponent(cpfTxt)
                    .addComponent(tipoTxt)
                    .addComponent(dataTxt)
                    .addComponent(ColumnTxt)
                    .addComponent(ColumnTxt1)
                    .addComponent(ColumnTxt2))
                .addContainerGap())
        );

        bodyBox.add(roll1Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 30));

        roll1Box1.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box1.setToolTipText("");
        roll1Box1.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box1.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box1MouseClicked(evt);
            }
        });

        protocoloTxt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt1.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt1.setText("IdProtocolo");

        cpfTxt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt1.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt1.setText("CPF");

        tipoTxt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt1.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt1.setText("tipo");

        dataTxt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt1.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt1.setText("data");

        ColumnTxt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt3.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt3.setText("|");

        ColumnTxt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt4.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt4.setText("|");

        ColumnTxt5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt5.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt5.setText("|");

        javax.swing.GroupLayout roll1Box1Layout = new javax.swing.GroupLayout(roll1Box1);
        roll1Box1.setLayout(roll1Box1Layout);
        roll1Box1Layout.setHorizontalGroup(
            roll1Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt1)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt1)
                .addGap(16, 16, 16))
        );
        roll1Box1Layout.setVerticalGroup(
            roll1Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt1)
                    .addComponent(cpfTxt1)
                    .addComponent(tipoTxt1)
                    .addComponent(dataTxt1)
                    .addComponent(ColumnTxt3)
                    .addComponent(ColumnTxt4)
                    .addComponent(ColumnTxt5))
                .addContainerGap())
        );

        bodyBox.add(roll1Box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 320, 30));

        roll1Box2.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box2.setToolTipText("");
        roll1Box2.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box2.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box2MouseClicked(evt);
            }
        });

        protocoloTxt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt2.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt2.setText("IdProtocolo");

        cpfTxt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt2.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt2.setText("CPF");

        tipoTxt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt2.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt2.setText("tipo");

        dataTxt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt2.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt2.setText("data");

        ColumnTxt6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt6.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt6.setText("|");

        ColumnTxt7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt7.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt7.setText("|");

        ColumnTxt8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt8.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt8.setText("|");

        javax.swing.GroupLayout roll1Box2Layout = new javax.swing.GroupLayout(roll1Box2);
        roll1Box2.setLayout(roll1Box2Layout);
        roll1Box2Layout.setHorizontalGroup(
            roll1Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt2)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt2)
                .addGap(16, 16, 16))
        );
        roll1Box2Layout.setVerticalGroup(
            roll1Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt2)
                    .addComponent(cpfTxt2)
                    .addComponent(tipoTxt2)
                    .addComponent(dataTxt2)
                    .addComponent(ColumnTxt6)
                    .addComponent(ColumnTxt7)
                    .addComponent(ColumnTxt8))
                .addContainerGap())
        );

        bodyBox.add(roll1Box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        roll1Box3.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box3.setToolTipText("");
        roll1Box3.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box3.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box3MouseClicked(evt);
            }
        });

        protocoloTxt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt3.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt3.setText("IdProtocolo");

        cpfTxt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt3.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt3.setText("CPF");

        tipoTxt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt3.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt3.setText("tipo");

        dataTxt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt3.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt3.setText("data");

        ColumnTxt9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt9.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt9.setText("|");

        ColumnTxt10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt10.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt10.setText("|");

        ColumnTxt11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt11.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt11.setText("|");

        javax.swing.GroupLayout roll1Box3Layout = new javax.swing.GroupLayout(roll1Box3);
        roll1Box3.setLayout(roll1Box3Layout);
        roll1Box3Layout.setHorizontalGroup(
            roll1Box3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt3)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt3)
                .addGap(16, 16, 16))
        );
        roll1Box3Layout.setVerticalGroup(
            roll1Box3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt3)
                    .addComponent(cpfTxt3)
                    .addComponent(tipoTxt3)
                    .addComponent(dataTxt3)
                    .addComponent(ColumnTxt9)
                    .addComponent(ColumnTxt10)
                    .addComponent(ColumnTxt11))
                .addContainerGap())
        );

        bodyBox.add(roll1Box3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 320, 30));

        roll1Box4.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box4.setToolTipText("");
        roll1Box4.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box4.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box4MouseClicked(evt);
            }
        });

        protocoloTxt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt4.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt4.setText("IdProtocolo");

        cpfTxt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt4.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt4.setText("CPF");

        tipoTxt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt4.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt4.setText("tipo");

        dataTxt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt4.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt4.setText("data");

        ColumnTxt12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt12.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt12.setText("|");

        ColumnTxt13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt13.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt13.setText("|");

        ColumnTxt14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt14.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt14.setText("|");

        javax.swing.GroupLayout roll1Box4Layout = new javax.swing.GroupLayout(roll1Box4);
        roll1Box4.setLayout(roll1Box4Layout);
        roll1Box4Layout.setHorizontalGroup(
            roll1Box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt4)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt4)
                .addGap(16, 16, 16))
        );
        roll1Box4Layout.setVerticalGroup(
            roll1Box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt4)
                    .addComponent(cpfTxt4)
                    .addComponent(tipoTxt4)
                    .addComponent(dataTxt4)
                    .addComponent(ColumnTxt12)
                    .addComponent(ColumnTxt13)
                    .addComponent(ColumnTxt14))
                .addContainerGap())
        );

        bodyBox.add(roll1Box4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 30));

        roll1Box5.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box5.setToolTipText("");
        roll1Box5.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box5.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box5MouseClicked(evt);
            }
        });

        protocoloTxt5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt5.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt5.setText("IdProtocolo");

        cpfTxt5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt5.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt5.setText("CPF");

        tipoTxt5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt5.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt5.setText("tipo");

        dataTxt5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt5.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt5.setText("data");

        ColumnTxt15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt15.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt15.setText("|");

        ColumnTxt16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt16.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt16.setText("|");

        ColumnTxt17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt17.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt17.setText("|");

        javax.swing.GroupLayout roll1Box5Layout = new javax.swing.GroupLayout(roll1Box5);
        roll1Box5.setLayout(roll1Box5Layout);
        roll1Box5Layout.setHorizontalGroup(
            roll1Box5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt5)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt5)
                .addGap(16, 16, 16))
        );
        roll1Box5Layout.setVerticalGroup(
            roll1Box5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt5)
                    .addComponent(cpfTxt5)
                    .addComponent(tipoTxt5)
                    .addComponent(dataTxt5)
                    .addComponent(ColumnTxt15)
                    .addComponent(ColumnTxt16)
                    .addComponent(ColumnTxt17))
                .addContainerGap())
        );

        bodyBox.add(roll1Box5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 320, 30));

        roll1Box6.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box6.setToolTipText("");
        roll1Box6.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box6.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box6MouseClicked(evt);
            }
        });

        protocoloTxt6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt6.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt6.setText("IdProtocolo");

        cpfTxt6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt6.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt6.setText("CPF");

        tipoTxt6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt6.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt6.setText("tipo");

        dataTxt6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt6.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt6.setText("data");

        ColumnTxt18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt18.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt18.setText("|");

        ColumnTxt19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt19.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt19.setText("|");

        ColumnTxt20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt20.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt20.setText("|");

        javax.swing.GroupLayout roll1Box6Layout = new javax.swing.GroupLayout(roll1Box6);
        roll1Box6.setLayout(roll1Box6Layout);
        roll1Box6Layout.setHorizontalGroup(
            roll1Box6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt6)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt20, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt6)
                .addGap(16, 16, 16))
        );
        roll1Box6Layout.setVerticalGroup(
            roll1Box6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt6)
                    .addComponent(cpfTxt6)
                    .addComponent(tipoTxt6)
                    .addComponent(dataTxt6)
                    .addComponent(ColumnTxt18)
                    .addComponent(ColumnTxt19)
                    .addComponent(ColumnTxt20))
                .addContainerGap())
        );

        bodyBox.add(roll1Box6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 320, 30));

        roll1Box7.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box7.setToolTipText("");
        roll1Box7.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box7.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box7MouseClicked(evt);
            }
        });

        protocoloTxt7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt7.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt7.setText("IdProtocolo");

        cpfTxt7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt7.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt7.setText("CPF");

        tipoTxt7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt7.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt7.setText("tipo");

        dataTxt7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt7.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt7.setText("data");

        ColumnTxt21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt21.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt21.setText("|");

        ColumnTxt22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt22.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt22.setText("|");

        ColumnTxt23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt23.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt23.setText("|");

        javax.swing.GroupLayout roll1Box7Layout = new javax.swing.GroupLayout(roll1Box7);
        roll1Box7.setLayout(roll1Box7Layout);
        roll1Box7Layout.setHorizontalGroup(
            roll1Box7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt7)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt23, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt7)
                .addGap(16, 16, 16))
        );
        roll1Box7Layout.setVerticalGroup(
            roll1Box7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt7)
                    .addComponent(cpfTxt7)
                    .addComponent(tipoTxt7)
                    .addComponent(dataTxt7)
                    .addComponent(ColumnTxt21)
                    .addComponent(ColumnTxt22)
                    .addComponent(ColumnTxt23))
                .addContainerGap())
        );

        bodyBox.add(roll1Box7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 320, 30));

        roll1Box8.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box8.setToolTipText("");
        roll1Box8.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box8.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box8MouseClicked(evt);
            }
        });

        protocoloTxt8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt8.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt8.setText("IdProtocolo");

        cpfTxt8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt8.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt8.setText("CPF");

        tipoTxt8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt8.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt8.setText("tipo");

        dataTxt8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt8.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt8.setText("data");

        ColumnTxt24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt24.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt24.setText("|");

        ColumnTxt25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt25.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt25.setText("|");

        ColumnTxt26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt26.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt26.setText("|");

        javax.swing.GroupLayout roll1Box8Layout = new javax.swing.GroupLayout(roll1Box8);
        roll1Box8.setLayout(roll1Box8Layout);
        roll1Box8Layout.setHorizontalGroup(
            roll1Box8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt8)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt26, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt8)
                .addGap(16, 16, 16))
        );
        roll1Box8Layout.setVerticalGroup(
            roll1Box8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt8)
                    .addComponent(cpfTxt8)
                    .addComponent(tipoTxt8)
                    .addComponent(dataTxt8)
                    .addComponent(ColumnTxt24)
                    .addComponent(ColumnTxt25)
                    .addComponent(ColumnTxt26))
                .addContainerGap())
        );

        bodyBox.add(roll1Box8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 30));

        roll1Box9.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box9.setToolTipText("");
        roll1Box9.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box9.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box9MouseClicked(evt);
            }
        });

        protocoloTxt9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt9.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt9.setText("IdProtocolo");

        cpfTxt9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt9.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt9.setText("CPF");

        tipoTxt9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt9.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt9.setText("tipo");

        dataTxt9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt9.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt9.setText("data");

        ColumnTxt27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt27.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt27.setText("|");

        ColumnTxt28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt28.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt28.setText("|");

        ColumnTxt29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt29.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt29.setText("|");

        javax.swing.GroupLayout roll1Box9Layout = new javax.swing.GroupLayout(roll1Box9);
        roll1Box9.setLayout(roll1Box9Layout);
        roll1Box9Layout.setHorizontalGroup(
            roll1Box9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt9)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt29, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt9)
                .addGap(16, 16, 16))
        );
        roll1Box9Layout.setVerticalGroup(
            roll1Box9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt9)
                    .addComponent(cpfTxt9)
                    .addComponent(tipoTxt9)
                    .addComponent(dataTxt9)
                    .addComponent(ColumnTxt27)
                    .addComponent(ColumnTxt28)
                    .addComponent(ColumnTxt29))
                .addContainerGap())
        );

        bodyBox.add(roll1Box9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 320, 30));

        roll1Box10.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box10.setToolTipText("");
        roll1Box10.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box10.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box10MouseClicked(evt);
            }
        });

        protocoloTxt10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt10.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt10.setText("IdProtocolo");

        cpfTxt10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt10.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt10.setText("CPF");

        tipoTxt10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt10.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt10.setText("tipo");

        dataTxt10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt10.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt10.setText("data");

        ColumnTxt30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt30.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt30.setText("|");

        ColumnTxt31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt31.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt31.setText("|");

        ColumnTxt32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt32.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt32.setText("|");

        javax.swing.GroupLayout roll1Box10Layout = new javax.swing.GroupLayout(roll1Box10);
        roll1Box10.setLayout(roll1Box10Layout);
        roll1Box10Layout.setHorizontalGroup(
            roll1Box10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt30, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt31, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt10)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt32, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt10)
                .addGap(16, 16, 16))
        );
        roll1Box10Layout.setVerticalGroup(
            roll1Box10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt10)
                    .addComponent(cpfTxt10)
                    .addComponent(tipoTxt10)
                    .addComponent(dataTxt10)
                    .addComponent(ColumnTxt30)
                    .addComponent(ColumnTxt31)
                    .addComponent(ColumnTxt32))
                .addContainerGap())
        );

        bodyBox.add(roll1Box10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 320, 30));

        roll1Box11.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box11.setToolTipText("");
        roll1Box11.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box11.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box11MouseClicked(evt);
            }
        });

        protocoloTxt11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt11.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt11.setText("IdProtocolo");

        cpfTxt11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt11.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt11.setText("CPF");

        tipoTxt11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt11.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt11.setText("tipo");

        dataTxt11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt11.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt11.setText("data");

        ColumnTxt33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt33.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt33.setText("|");

        ColumnTxt34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt34.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt34.setText("|");

        ColumnTxt35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt35.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt35.setText("|");

        javax.swing.GroupLayout roll1Box11Layout = new javax.swing.GroupLayout(roll1Box11);
        roll1Box11.setLayout(roll1Box11Layout);
        roll1Box11Layout.setHorizontalGroup(
            roll1Box11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt33, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt34, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt11)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt35, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt11)
                .addGap(16, 16, 16))
        );
        roll1Box11Layout.setVerticalGroup(
            roll1Box11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt11)
                    .addComponent(cpfTxt11)
                    .addComponent(tipoTxt11)
                    .addComponent(dataTxt11)
                    .addComponent(ColumnTxt33)
                    .addComponent(ColumnTxt34)
                    .addComponent(ColumnTxt35))
                .addContainerGap())
        );

        bodyBox.add(roll1Box11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 320, 30));

        roll1Box12.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box12.setToolTipText("");
        roll1Box12.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box12.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box12MouseClicked(evt);
            }
        });

        protocoloTxt12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt12.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt12.setText("IdProtocolo");

        cpfTxt12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt12.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt12.setText("CPF");

        tipoTxt12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt12.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt12.setText("tipo");

        dataTxt12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt12.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt12.setText("data");

        ColumnTxt36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt36.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt36.setText("|");

        ColumnTxt37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt37.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt37.setText("|");

        ColumnTxt38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt38.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt38.setText("|");

        javax.swing.GroupLayout roll1Box12Layout = new javax.swing.GroupLayout(roll1Box12);
        roll1Box12.setLayout(roll1Box12Layout);
        roll1Box12Layout.setHorizontalGroup(
            roll1Box12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt36, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt37, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt12)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt38, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt12)
                .addGap(16, 16, 16))
        );
        roll1Box12Layout.setVerticalGroup(
            roll1Box12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt12)
                    .addComponent(cpfTxt12)
                    .addComponent(tipoTxt12)
                    .addComponent(dataTxt12)
                    .addComponent(ColumnTxt36)
                    .addComponent(ColumnTxt37)
                    .addComponent(ColumnTxt38))
                .addContainerGap())
        );

        bodyBox.add(roll1Box12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 320, 30));

        roll1Box13.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box13.setToolTipText("");
        roll1Box13.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box13.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box13MouseClicked(evt);
            }
        });

        protocoloTxt13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt13.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt13.setText("IdProtocolo");

        cpfTxt13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt13.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt13.setText("CPF");

        tipoTxt13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt13.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt13.setText("tipo");

        dataTxt13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt13.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt13.setText("data");

        ColumnTxt39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt39.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt39.setText("|");

        ColumnTxt40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt40.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt40.setText("|");

        ColumnTxt41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt41.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt41.setText("|");

        javax.swing.GroupLayout roll1Box13Layout = new javax.swing.GroupLayout(roll1Box13);
        roll1Box13.setLayout(roll1Box13Layout);
        roll1Box13Layout.setHorizontalGroup(
            roll1Box13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt39, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt40, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt13)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt41, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt13)
                .addGap(16, 16, 16))
        );
        roll1Box13Layout.setVerticalGroup(
            roll1Box13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt13)
                    .addComponent(cpfTxt13)
                    .addComponent(tipoTxt13)
                    .addComponent(dataTxt13)
                    .addComponent(ColumnTxt39)
                    .addComponent(ColumnTxt40)
                    .addComponent(ColumnTxt41))
                .addContainerGap())
        );

        bodyBox.add(roll1Box13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 320, 30));

        roll1Box14.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box14.setToolTipText("");
        roll1Box14.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box14.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box14MouseClicked(evt);
            }
        });

        protocoloTxt14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt14.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt14.setText("IdProtocolo");

        cpfTxt14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt14.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt14.setText("CPF");

        tipoTxt14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt14.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt14.setText("tipo");

        dataTxt14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt14.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt14.setText("data");

        ColumnTxt42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt42.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt42.setText("|");

        ColumnTxt43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt43.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt43.setText("|");

        ColumnTxt44.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt44.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt44.setText("|");

        javax.swing.GroupLayout roll1Box14Layout = new javax.swing.GroupLayout(roll1Box14);
        roll1Box14.setLayout(roll1Box14Layout);
        roll1Box14Layout.setHorizontalGroup(
            roll1Box14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box14Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt42, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt43, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt14)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt44, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt14)
                .addGap(16, 16, 16))
        );
        roll1Box14Layout.setVerticalGroup(
            roll1Box14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt14)
                    .addComponent(cpfTxt14)
                    .addComponent(tipoTxt14)
                    .addComponent(dataTxt14)
                    .addComponent(ColumnTxt42)
                    .addComponent(ColumnTxt43)
                    .addComponent(ColumnTxt44))
                .addContainerGap())
        );

        bodyBox.add(roll1Box14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 320, 30));

        roll1Box15.setBackground(new java.awt.Color(5, 7, 54));
        roll1Box15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        roll1Box15.setToolTipText("");
        roll1Box15.setMaximumSize(new java.awt.Dimension(351, 163));
        roll1Box15.setPreferredSize(new java.awt.Dimension(351, 163));
        roll1Box15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roll1Box15MouseClicked(evt);
            }
        });

        protocoloTxt15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        protocoloTxt15.setForeground(new java.awt.Color(255, 255, 102));
        protocoloTxt15.setText("IdProtocolo");

        cpfTxt15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cpfTxt15.setForeground(new java.awt.Color(255, 255, 102));
        cpfTxt15.setText("CPF");

        tipoTxt15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoTxt15.setForeground(new java.awt.Color(255, 255, 102));
        tipoTxt15.setText("tipo");

        dataTxt15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dataTxt15.setForeground(new java.awt.Color(255, 255, 102));
        dataTxt15.setText("data");

        ColumnTxt45.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt45.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt45.setText("|");

        ColumnTxt46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt46.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt46.setText("|");

        ColumnTxt47.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ColumnTxt47.setForeground(new java.awt.Color(255, 255, 102));
        ColumnTxt47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColumnTxt47.setText("|");

        javax.swing.GroupLayout roll1Box15Layout = new javax.swing.GroupLayout(roll1Box15);
        roll1Box15.setLayout(roll1Box15Layout);
        roll1Box15Layout.setHorizontalGroup(
            roll1Box15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roll1Box15Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(protocoloTxt15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ColumnTxt45, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cpfTxt15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ColumnTxt46, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoTxt15)
                .addGap(17, 17, 17)
                .addComponent(ColumnTxt47, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataTxt15)
                .addGap(16, 16, 16))
        );
        roll1Box15Layout.setVerticalGroup(
            roll1Box15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roll1Box15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roll1Box15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(protocoloTxt15)
                    .addComponent(cpfTxt15)
                    .addComponent(tipoTxt15)
                    .addComponent(dataTxt15)
                    .addComponent(ColumnTxt45)
                    .addComponent(ColumnTxt46)
                    .addComponent(ColumnTxt47))
                .addContainerGap())
        );

        bodyBox.add(roll1Box15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 320, 30));

        footerBox.setOpaque(false);

        squareTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        squareTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        squareTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/squareBttn.png"))); // NOI18N

        ballTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ballTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/circleBttn.png"))); // NOI18N

        backTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backBttn.png"))); // NOI18N
        backTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout footerBoxLayout = new javax.swing.GroupLayout(footerBox);
        footerBox.setLayout(footerBoxLayout);
        footerBoxLayout.setHorizontalGroup(
            footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerBoxLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(squareTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ballTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backTxt)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        footerBoxLayout.setVerticalGroup(
            footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerBoxLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(squareTxt)
                    .addGroup(footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ballTxt)
                        .addComponent(backTxt)))
                .addContainerGap())
        );

        bodyBox.add(footerBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 310, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bg.png"))); // NOI18N

        javax.swing.GroupLayout bgBoxLayout = new javax.swing.GroupLayout(bgBox);
        bgBox.setLayout(bgBoxLayout);
        bgBoxLayout.setHorizontalGroup(
            bgBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgBoxLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(bodyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(bgBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgBoxLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        bgBoxLayout.setVerticalGroup(
            bgBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgBoxLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bodyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(bgBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgBoxLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(bgBox);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static int i;
    
    
    private void escondidinho(){
        adm2.setVisible(true);
        this.setVisible(false);
    }
       
    private void roll1Box1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box1MouseClicked
        escondidinho();
        i = 2;
    }//GEN-LAST:event_roll1Box1MouseClicked

    private void roll1BoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1BoxMouseClicked
        i = 1;
        escondidinho();
    }//GEN-LAST:event_roll1BoxMouseClicked

    private void roll1Box2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box2MouseClicked
        i = 3;
        escondidinho();
    }//GEN-LAST:event_roll1Box2MouseClicked

    private void roll1Box3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box3MouseClicked
       i = 4;
        escondidinho();
    }//GEN-LAST:event_roll1Box3MouseClicked

    private void roll1Box4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box4MouseClicked
       i = 5;
        escondidinho();
    }//GEN-LAST:event_roll1Box4MouseClicked

    private void roll1Box5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box5MouseClicked
      i = 6;
       escondidinho();
    }//GEN-LAST:event_roll1Box5MouseClicked

    private void roll1Box6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box6MouseClicked
       i = 7;
        escondidinho();
    }//GEN-LAST:event_roll1Box6MouseClicked

    private void roll1Box7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box7MouseClicked
       i = 8;
        escondidinho();
    }//GEN-LAST:event_roll1Box7MouseClicked

    private void roll1Box8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box8MouseClicked
       i = 9;
        escondidinho();
    }//GEN-LAST:event_roll1Box8MouseClicked

    private void roll1Box9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box9MouseClicked
        i = 10;
        escondidinho();
    }//GEN-LAST:event_roll1Box9MouseClicked

    private void roll1Box10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box10MouseClicked
        i = 11;
        escondidinho();
    }//GEN-LAST:event_roll1Box10MouseClicked

    private void roll1Box11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box11MouseClicked
        i = 12;
        escondidinho();
    }//GEN-LAST:event_roll1Box11MouseClicked

    private void roll1Box12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box12MouseClicked
       i = 13;
        escondidinho();
    }//GEN-LAST:event_roll1Box12MouseClicked

    private void roll1Box13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box13MouseClicked
        i = 14;
        escondidinho();
    }//GEN-LAST:event_roll1Box13MouseClicked

    private void roll1Box14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box14MouseClicked
        i = 15;
        escondidinho();
    }//GEN-LAST:event_roll1Box14MouseClicked

    private void roll1Box15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roll1Box15MouseClicked
        i = 16;
        escondidinho();
    }//GEN-LAST:event_roll1Box15MouseClicked
    public JLabel[] protoText(){
        JLabel[] protocolo = new JLabel[]{protocoloTxt, protocoloTxt1, protocoloTxt2, protocoloTxt3, protocoloTxt4, protocoloTxt5,
        protocoloTxt6, protocoloTxt7, protocoloTxt8, protocoloTxt9, protocoloTxt10, protocoloTxt11, protocoloTxt12, protocoloTxt13,
        protocoloTxt14, protocoloTxt15};
        
        return protocolo;
    }
    
    public JLabel[] cpfText(){
        JLabel[] cpf = new JLabel[]{cpfTxt, cpfTxt1, cpfTxt2, cpfTxt3, cpfTxt4, cpfTxt5,
        cpfTxt6, cpfTxt7, cpfTxt8, cpfTxt9, cpfTxt10, cpfTxt11, cpfTxt12, cpfTxt13,
        cpfTxt14, cpfTxt15};
        
        return cpf;
    }
    
    public JLabel[] tipoText(){
        JLabel[] tipo = new JLabel[]{tipoTxt, tipoTxt1, tipoTxt2, tipoTxt3, tipoTxt4, tipoTxt5,
        tipoTxt6, tipoTxt7, tipoTxt8, tipoTxt9, tipoTxt10, tipoTxt11, tipoTxt12, tipoTxt13,
        tipoTxt14, tipoTxt15};
        
        return tipo;
    }
    
    public JLabel[] dataText(){
        JLabel[] data = new JLabel[]{dataTxt, dataTxt1, dataTxt2, dataTxt3, dataTxt4, dataTxt5,
        dataTxt6, dataTxt7, dataTxt8, dataTxt9, dataTxt10, dataTxt11, dataTxt12, dataTxt13,
        dataTxt14, dataTxt15};
        
        return data;
    }
    
    private JPanel[] roll(){
        JPanel[] roll = new JPanel[]{roll1Box, roll1Box1, roll1Box2, roll1Box3, roll1Box4, roll1Box5, roll1Box6, roll1Box7,
        roll1Box8, roll1Box9, roll1Box10, roll1Box11, roll1Box12, roll1Box13, roll1Box14, roll1Box15};
        
        return roll;
    }
    
    protected static String[] newProto, newCpf, newData, newTipo;
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (int i = 0; i < 16; i++) {
            roll()[i].setVisible(false);
        }
        
        try {
            conn = DriverManager.getConnection(host, user, password);
            stmt = conn.createStatement();
            
            rs = stmt.executeQuery("Select id FROM protocolo");
            int i, j = 0;
            
            while (rs.next() == true){
                roll()[j].setVisible(true);
                j++;
            }
            
            rs = stmt.executeQuery("Select * FROM protocolo");
            
            i = 0;
            while (rs.next()){
                protoText()[i].setText(rs.getString("id_protocolo"));
                cpfText()[i].setText(rs.getString("cpf_cliente"));
                dataText()[i].setText(rs.getString("data"));
                tipoText()[i].setText(rs.getString("tipo"));
                i++;
            }
        } catch (SQLException e){
            throw new IllegalStateException("FALHA AO CONECTAR AO BANCO DE DADOS", e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void backTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseClicked
        LoginScreen login = new LoginScreen();
        this.setVisible(false); 
        login.setVisible(true);
    }//GEN-LAST:event_backTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColumnTxt;
    private javax.swing.JLabel ColumnTxt1;
    private javax.swing.JLabel ColumnTxt10;
    private javax.swing.JLabel ColumnTxt11;
    private javax.swing.JLabel ColumnTxt12;
    private javax.swing.JLabel ColumnTxt13;
    private javax.swing.JLabel ColumnTxt14;
    private javax.swing.JLabel ColumnTxt15;
    private javax.swing.JLabel ColumnTxt16;
    private javax.swing.JLabel ColumnTxt17;
    private javax.swing.JLabel ColumnTxt18;
    private javax.swing.JLabel ColumnTxt19;
    private javax.swing.JLabel ColumnTxt2;
    private javax.swing.JLabel ColumnTxt20;
    private javax.swing.JLabel ColumnTxt21;
    private javax.swing.JLabel ColumnTxt22;
    private javax.swing.JLabel ColumnTxt23;
    private javax.swing.JLabel ColumnTxt24;
    private javax.swing.JLabel ColumnTxt25;
    private javax.swing.JLabel ColumnTxt26;
    private javax.swing.JLabel ColumnTxt27;
    private javax.swing.JLabel ColumnTxt28;
    private javax.swing.JLabel ColumnTxt29;
    private javax.swing.JLabel ColumnTxt3;
    private javax.swing.JLabel ColumnTxt30;
    private javax.swing.JLabel ColumnTxt31;
    private javax.swing.JLabel ColumnTxt32;
    private javax.swing.JLabel ColumnTxt33;
    private javax.swing.JLabel ColumnTxt34;
    private javax.swing.JLabel ColumnTxt35;
    private javax.swing.JLabel ColumnTxt36;
    private javax.swing.JLabel ColumnTxt37;
    private javax.swing.JLabel ColumnTxt38;
    private javax.swing.JLabel ColumnTxt39;
    private javax.swing.JLabel ColumnTxt4;
    private javax.swing.JLabel ColumnTxt40;
    private javax.swing.JLabel ColumnTxt41;
    private javax.swing.JLabel ColumnTxt42;
    private javax.swing.JLabel ColumnTxt43;
    private javax.swing.JLabel ColumnTxt44;
    private javax.swing.JLabel ColumnTxt45;
    private javax.swing.JLabel ColumnTxt46;
    private javax.swing.JLabel ColumnTxt47;
    private javax.swing.JLabel ColumnTxt5;
    private javax.swing.JLabel ColumnTxt6;
    private javax.swing.JLabel ColumnTxt7;
    private javax.swing.JLabel ColumnTxt8;
    private javax.swing.JLabel ColumnTxt9;
    private javax.swing.JLabel backTxt;
    private javax.swing.JLabel ballTxt;
    private javax.swing.JPanel bgBox;
    private javax.swing.JPanel bodyBox;
    private javax.swing.JLabel cpfTxt;
    private javax.swing.JLabel cpfTxt1;
    private javax.swing.JLabel cpfTxt10;
    private javax.swing.JLabel cpfTxt11;
    private javax.swing.JLabel cpfTxt12;
    private javax.swing.JLabel cpfTxt13;
    private javax.swing.JLabel cpfTxt14;
    private javax.swing.JLabel cpfTxt15;
    private javax.swing.JLabel cpfTxt2;
    private javax.swing.JLabel cpfTxt3;
    private javax.swing.JLabel cpfTxt4;
    private javax.swing.JLabel cpfTxt5;
    private javax.swing.JLabel cpfTxt6;
    private javax.swing.JLabel cpfTxt7;
    private javax.swing.JLabel cpfTxt8;
    private javax.swing.JLabel cpfTxt9;
    private javax.swing.JLabel dataTxt;
    private javax.swing.JLabel dataTxt1;
    private javax.swing.JLabel dataTxt10;
    private javax.swing.JLabel dataTxt11;
    private javax.swing.JLabel dataTxt12;
    private javax.swing.JLabel dataTxt13;
    private javax.swing.JLabel dataTxt14;
    private javax.swing.JLabel dataTxt15;
    private javax.swing.JLabel dataTxt2;
    private javax.swing.JLabel dataTxt3;
    private javax.swing.JLabel dataTxt4;
    private javax.swing.JLabel dataTxt5;
    private javax.swing.JLabel dataTxt6;
    private javax.swing.JLabel dataTxt7;
    private javax.swing.JLabel dataTxt8;
    private javax.swing.JLabel dataTxt9;
    private javax.swing.JPanel footerBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel protocoloTxt;
    private javax.swing.JLabel protocoloTxt1;
    private javax.swing.JLabel protocoloTxt10;
    private javax.swing.JLabel protocoloTxt11;
    private javax.swing.JLabel protocoloTxt12;
    private javax.swing.JLabel protocoloTxt13;
    private javax.swing.JLabel protocoloTxt14;
    private javax.swing.JLabel protocoloTxt15;
    private javax.swing.JLabel protocoloTxt2;
    private javax.swing.JLabel protocoloTxt3;
    private javax.swing.JLabel protocoloTxt4;
    private javax.swing.JLabel protocoloTxt5;
    private javax.swing.JLabel protocoloTxt6;
    private javax.swing.JLabel protocoloTxt7;
    private javax.swing.JLabel protocoloTxt8;
    private javax.swing.JLabel protocoloTxt9;
    private javax.swing.JPanel roll1Box;
    private javax.swing.JPanel roll1Box1;
    private javax.swing.JPanel roll1Box10;
    private javax.swing.JPanel roll1Box11;
    private javax.swing.JPanel roll1Box12;
    private javax.swing.JPanel roll1Box13;
    private javax.swing.JPanel roll1Box14;
    private javax.swing.JPanel roll1Box15;
    private javax.swing.JPanel roll1Box2;
    private javax.swing.JPanel roll1Box3;
    private javax.swing.JPanel roll1Box4;
    private javax.swing.JPanel roll1Box5;
    private javax.swing.JPanel roll1Box6;
    private javax.swing.JPanel roll1Box7;
    private javax.swing.JPanel roll1Box8;
    private javax.swing.JPanel roll1Box9;
    private javax.swing.JLabel squareTxt;
    private javax.swing.JLabel tipoTxt;
    private javax.swing.JLabel tipoTxt1;
    private javax.swing.JLabel tipoTxt10;
    private javax.swing.JLabel tipoTxt11;
    private javax.swing.JLabel tipoTxt12;
    private javax.swing.JLabel tipoTxt13;
    private javax.swing.JLabel tipoTxt14;
    private javax.swing.JLabel tipoTxt15;
    private javax.swing.JLabel tipoTxt2;
    private javax.swing.JLabel tipoTxt3;
    private javax.swing.JLabel tipoTxt4;
    private javax.swing.JLabel tipoTxt5;
    private javax.swing.JLabel tipoTxt6;
    private javax.swing.JLabel tipoTxt7;
    private javax.swing.JLabel tipoTxt8;
    private javax.swing.JLabel tipoTxt9;
    // End of variables declaration//GEN-END:variables
}
