/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Code;

import java.awt.Color;
import Auxiliar.SQL.*;

/**
 *
 * @author joao-
 */
public class LoginScreen extends javax.swing.JFrame {
    Retrieve pull = new Retrieve();
    Updates updateSql = new Updates();
    /**
     * Creates new form Login
     */
    
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgBox = new javax.swing.JPanel();
        Box = new javax.swing.JPanel();
        PasswordTxt = new javax.swing.JLabel();
        NumAgenField = new javax.swing.JTextField();
        NumAgenTxt = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginBttn = new javax.swing.JButton();
        LembremeChxBox = new javax.swing.JCheckBox();
        MensagemTxt = new javax.swing.JLabel();
        BgImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BgBox.setLayout(new javax.swing.OverlayLayout(BgBox));

        Box.setAlignmentY(0.5F);
        Box.setOpaque(false);
        Box.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordTxt.setBackground(new java.awt.Color(14, 0, 35));
        PasswordTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PasswordTxt.setText("Senha");
        PasswordTxt.setOpaque(true);
        Box.add(PasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        NumAgenField.setBackground(new java.awt.Color(6, 8, 66));
        NumAgenField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        NumAgenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumAgenFieldActionPerformed(evt);
            }
        });
        Box.add(NumAgenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 250, 30));

        NumAgenTxt.setBackground(new java.awt.Color(14, 0, 35));
        NumAgenTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NumAgenTxt.setText("Agência");
        NumAgenTxt.setOpaque(true);
        Box.add(NumAgenTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        PasswordField.setBackground(new java.awt.Color(6, 8, 66));
        PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        Box.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 260, 30));

        LoginBttn.setBackground(new java.awt.Color(14, 0, 35));
        LoginBttn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LoginBttn.setForeground(new java.awt.Color(255, 255, 51));
        LoginBttn.setText("Login");
        LoginBttn.setToolTipText("");
        LoginBttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        LoginBttn.setName("loginbttn"); // NOI18N
        LoginBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginBttnMouseClicked(evt);
            }
        });
        LoginBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBttnActionPerformed(evt);
            }
        });
        Box.add(LoginBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 80, 30));

        LembremeChxBox.setText("Lembre-me");
        LembremeChxBox.setName("boleano"); // NOI18N
        LembremeChxBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LembremeChxBoxActionPerformed(evt);
            }
        });
        Box.add(LembremeChxBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, -1));

        MensagemTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MensagemTxt.setForeground(new java.awt.Color(255, 0, 51));
        MensagemTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensagemTxt.setText("Senha incorreta!");
        Box.add(MensagemTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 200, 50));

        BgBox.add(Box);

        BgImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bg.png"))); // NOI18N
        BgBox.add(BgImg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgBox, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumAgenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumAgenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumAgenFieldActionPerformed

    private void LoginBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBttnActionPerformed
        
    }//GEN-LAST:event_LoginBttnActionPerformed

    private void LembremeChxBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LembremeChxBoxActionPerformed
        updateSql.updateSQLBoleano(LembremeChxBox.isSelected());
    }//GEN-LAST:event_LembremeChxBoxActionPerformed

    private void LoginBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginBttnMouseClicked
        if (NumAgenField.getText().equalsIgnoreCase(pull.selectAgencia()) && PasswordField.getText().equalsIgnoreCase(pull.selectSenha())){
            UsuarioScreen user = new UsuarioScreen();
            user.setVisible(true); //mostra os componentes da próxima janela
            this.setVisible(false); //esconde os componentes dessa janela
        }
        else if(NumAgenField.getText().equalsIgnoreCase("admin") && PasswordField.getText().equalsIgnoreCase(pull.selectSenhaAdm())){
            AdmScreen adm = new AdmScreen();
            this.setVisible(false);
            adm.setVisible(true);
        }else{
            MensagemTxt.setVisible(true);
            MensagemTxt.setText("Senha/Agencia incorretos!");
        }
    }//GEN-LAST:event_LoginBttnMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        PasswordTxt.setForeground(Color.white);
        MensagemTxt.setForeground(Color.red);
        NumAgenTxt.setForeground(Color.white);
        NumAgenField.setForeground(Color.white);
        PasswordField.setForeground(Color.white);
        LembremeChxBox.setForeground(Color.white);
        MensagemTxt.setVisible(false);
        if (pull.selectBooleano().equals("0")){
            LembremeChxBox.setSelected(false);
        }
        else{
            LembremeChxBox.setSelected(true);
        }
        
        if (LembremeChxBox.isSelected()){
            UsuarioScreen user = new UsuarioScreen();
            this.setVisible(false);
            user.setVisible(true);
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    public void setLembreme(boolean x){
        this.LembremeChxBox.setSelected(x);
        updateSql.updateSQLBoleano(x);
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgBox;
    private javax.swing.JLabel BgImg;
    private javax.swing.JPanel Box;
    private javax.swing.JCheckBox LembremeChxBox;
    private javax.swing.JButton LoginBttn;
    private javax.swing.JLabel MensagemTxt;
    private javax.swing.JTextField NumAgenField;
    private javax.swing.JLabel NumAgenTxt;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordTxt;
    // End of variables declaration//GEN-END:variables

    private void setSelected(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
