/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Code;

    import java.awt.Color;
    import Auxiliar.Parse;
    import Auxiliar.SQL.*;
public class UsuarioScreen extends javax.swing.JFrame {
    
    private static int check = 0;
    private static int checkBttn;
    
    private static Adm2Screen adm2 = new Adm2Screen();
    private static Parse parse = new Parse();
    Adm2Screen admCheck = new Adm2Screen();
    private Retrieve get = new Retrieve();
    Updates updateSql = new Updates();
    
    /**
     * Creates new form UsuarioScreen1
     */
    public UsuarioScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgBox = new javax.swing.JPanel();
        HeaderBox = new javax.swing.JPanel();
        profileImg = new javax.swing.JLabel();
        welcomeTxt = new javax.swing.JLabel();
        bodyBox = new javax.swing.JPanel();
        moneyBox = new javax.swing.JPanel();
        valorTxt = new javax.swing.JLabel();
        userSetValor = new javax.swing.JTextField();
        nextBttn = new javax.swing.JButton();
        moneyTxt = new javax.swing.JLabel();
        text1Txt = new javax.swing.JLabel();
        extractBttn = new javax.swing.JButton();
        depositBttn1 = new javax.swing.JButton();
        extractTxt = new javax.swing.JLabel();
        depositTxt1 = new javax.swing.JLabel();
        helpBox = new javax.swing.JPanel();
        helpBttn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        footerBox = new javax.swing.JPanel();
        squareTxt = new javax.swing.JLabel();
        ballTxt = new javax.swing.JLabel();
        backTxt = new javax.swing.JLabel();
        moneyTxt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BgBox.setBackground(new java.awt.Color(0, 0, 0));
        BgBox.setPreferredSize(new java.awt.Dimension(403, 802));
        BgBox.setLayout(new javax.swing.OverlayLayout(BgBox));

        HeaderBox.setBackground(new java.awt.Color(6, 8, 66));
        HeaderBox.setMaximumSize(new java.awt.Dimension(403, 152));
        HeaderBox.setPreferredSize(new java.awt.Dimension(403, 52));
        HeaderBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profileImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/profilepic.png"))); // NOI18N
        profileImg.setName(""); // NOI18N
        HeaderBox.add(profileImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 90));

        welcomeTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeTxt.setText("Olá, Usuario!");
        HeaderBox.add(welcomeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        BgBox.add(HeaderBox);

        bodyBox.setOpaque(false);
        bodyBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        moneyBox.setBackground(new java.awt.Color(19, 19, 19));
        moneyBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        valorTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        valorTxt.setText("Digite o valor que deseja depositar");

        userSetValor.setBackground(new java.awt.Color(28, 28, 28));
        userSetValor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userSetValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        userSetValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSetValorActionPerformed(evt);
            }
        });

        nextBttn.setBackground(new java.awt.Color(19, 19, 19));
        nextBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nextBttn.png"))); // NOI18N
        nextBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextBttnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout moneyBoxLayout = new javax.swing.GroupLayout(moneyBox);
        moneyBox.setLayout(moneyBoxLayout);
        moneyBoxLayout.setHorizontalGroup(
            moneyBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moneyBoxLayout.createSequentialGroup()
                .addGroup(moneyBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moneyBoxLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(valorTxt))
                    .addGroup(moneyBoxLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(userSetValor, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(moneyBoxLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(nextBttn)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        moneyBoxLayout.setVerticalGroup(
            moneyBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moneyBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(valorTxt)
                .addGap(18, 18, 18)
                .addComponent(userSetValor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBttn)
                .addGap(15, 15, 15))
        );

        bodyBox.add(moneyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 360, 200));

        moneyTxt.setBackground(new java.awt.Color(0, 0, 0));
        moneyTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        moneyTxt.setText("00.00");
        bodyBox.add(moneyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        text1Txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text1Txt.setText("Seu saldo é");
        bodyBox.add(text1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        extractBttn.setBackground(new java.awt.Color(0, 0, 0));
        extractBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ExtratoBttn.png"))); // NOI18N
        extractBttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        extractBttn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        extractBttn.setName("extractBttn"); // NOI18N
        extractBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extractBttnMouseClicked(evt);
            }
        });
        extractBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractBttnActionPerformed(evt);
            }
        });
        bodyBox.add(extractBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 80, 70));

        depositBttn1.setBackground(new java.awt.Color(0, 0, 0));
        depositBttn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DepositoBttn.png"))); // NOI18N
        depositBttn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        depositBttn1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        depositBttn1.setName("depositBttn"); // NOI18N
        depositBttn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositBttn1MouseClicked(evt);
            }
        });
        depositBttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBttn1ActionPerformed(evt);
            }
        });
        bodyBox.add(depositBttn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 80, 70));

        extractTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        extractTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        extractTxt.setText("Extrair");
        bodyBox.add(extractTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 80, -1));

        depositTxt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        depositTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        depositTxt1.setText("Depósitar");
        bodyBox.add(depositTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 80, -1));

        helpBox.setBackground(new java.awt.Color(15, 15, 15));

        helpBttn.setBackground(new java.awt.Color(38, 32, 32));
        helpBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/HelpBttn.png"))); // NOI18N
        helpBttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        helpBttn.setOpaque(true);
        helpBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpBttnMouseClicked(evt);
            }
        });
        helpBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBttnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Precisando de ajuda?");

        javax.swing.GroupLayout helpBoxLayout = new javax.swing.GroupLayout(helpBox);
        helpBox.setLayout(helpBoxLayout);
        helpBoxLayout.setHorizontalGroup(
            helpBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpBoxLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(helpBttn)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        helpBoxLayout.setVerticalGroup(
            helpBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpBoxLayout.createSequentialGroup()
                .addGroup(helpBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helpBoxLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(helpBttn))
                    .addGroup(helpBoxLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bodyBox.add(helpBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 350, -1));

        footerBox.setOpaque(false);

        squareTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        squareTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        squareTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/squareBttn.png"))); // NOI18N

        ballTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ballTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/circleBttn.png"))); // NOI18N

        backTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backBttn.png"))); // NOI18N
        backTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout footerBoxLayout = new javax.swing.GroupLayout(footerBox);
        footerBox.setLayout(footerBoxLayout);
        footerBoxLayout.setHorizontalGroup(
            footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerBoxLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(squareTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ballTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backTxt)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        footerBoxLayout.setVerticalGroup(
            footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(footerBoxLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(squareTxt))
                    .addGroup(footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ballTxt)
                        .addComponent(backTxt)))
                .addContainerGap())
        );

        bodyBox.add(footerBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 370, 50));

        moneyTxt1.setBackground(new java.awt.Color(0, 0, 0));
        moneyTxt1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        moneyTxt1.setText("R$:");
        bodyBox.add(moneyTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 70));

        BgBox.add(bodyBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgBox, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgBox, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extractBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractBttnActionPerformed

    }//GEN-LAST:event_extractBttnActionPerformed

    private void depositBttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBttn1ActionPerformed

    }//GEN-LAST:event_depositBttn1ActionPerformed

    private void helpBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpBttnMouseClicked
        Usuario2Screen help = new Usuario2Screen();
        this.setVisible(false);
        help.setVisible(true);
    }//GEN-LAST:event_helpBttnMouseClicked

    private void helpBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBttnActionPerformed

    }//GEN-LAST:event_helpBttnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        depositTxt1.setForeground(Color.white);
        extractTxt.setForeground(Color.white);
        moneyTxt.setForeground(Color.white);
        moneyTxt1.setForeground(Color.white);
        welcomeTxt.setForeground(Color.white);
        text1Txt.setForeground(Color.white);
        jLabel1.setForeground(Color.white);
        moneyBox.setVisible(false);
        valorTxt.setForeground(Color.white);
        userSetValor.setForeground(Color.white);
        moneyTxt.setText(get.selectSaldo());
    }//GEN-LAST:event_formWindowOpened

    private void backTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseClicked
        if (check == 0){
            LoginScreen login = new LoginScreen();
            this.setVisible(false);
            login.setVisible(true);
            login.setLembreme(false);
        } else{
            moneyBox.setVisible(false);
            check = 0;
        }
    }//GEN-LAST:event_backTxtMouseClicked

    private void depositBttn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositBttn1MouseClicked
        if (get.selectDepositoBol().equals("1")){
            valorTxt.setText("Digite o valor que deseja depositar");
            userSetValor.setText("");
            moneyBox.setVisible(true);
            check = 1;
            checkBttn = 0;
        }
    }//GEN-LAST:event_depositBttn1MouseClicked
    
    private void nextBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBttnMouseClicked
        if (userSetValor.getText().isEmpty()){
            moneyBox.setVisible(false);
        }else{
            if (checkBttn == 0){    
                String parseStr = Double.toString(parse.parseDoublePlus(moneyTxt.getText(), userSetValor.getText()));
                moneyTxt.setText(parseStr);
                updateSql.updateSQLSaldo(moneyTxt.getText());
                moneyBox.setVisible(false);
            }
            else{
                String parseStr = Double.toString(parse.parseDoubleMinus(moneyTxt.getText(), userSetValor.getText()));
                moneyTxt.setText(parseStr);
                updateSql.updateSQLSaldo(moneyTxt.getText());
                moneyBox.setVisible(false);
            }
        }
    }//GEN-LAST:event_nextBttnMouseClicked

    private void userSetValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSetValorActionPerformed

    }//GEN-LAST:event_userSetValorActionPerformed

    private void extractBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extractBttnMouseClicked
        if (get.selectExtratoBol().equals("1")){    
            valorTxt.setText("Digite o valor que deseja extrair");
            userSetValor.setText("");
            moneyBox.setVisible(true);
            checkBttn = 1;
            check = 1;
        }
    }//GEN-LAST:event_extractBttnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgBox;
    private javax.swing.JPanel HeaderBox;
    private javax.swing.JLabel backTxt;
    private javax.swing.JLabel ballTxt;
    private javax.swing.JPanel bodyBox;
    private javax.swing.JButton depositBttn1;
    private javax.swing.JLabel depositTxt1;
    private javax.swing.JButton extractBttn;
    private javax.swing.JLabel extractTxt;
    private javax.swing.JPanel footerBox;
    private javax.swing.JPanel helpBox;
    private javax.swing.JButton helpBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel moneyBox;
    private javax.swing.JLabel moneyTxt;
    private javax.swing.JLabel moneyTxt1;
    private javax.swing.JButton nextBttn;
    private javax.swing.JLabel profileImg;
    private javax.swing.JLabel squareTxt;
    private javax.swing.JLabel text1Txt;
    private javax.swing.JTextField userSetValor;
    private javax.swing.JLabel valorTxt;
    private javax.swing.JLabel welcomeTxt;
    // End of variables declaration//GEN-END:variables
}
