/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Code;

import java.awt.Color;
import Auxiliar.SQL.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
/**
 *
 * @author Alunos
 */
public class Usuario2Screen extends javax.swing.JFrame {
    Inserts inset = new Inserts();
    DateTimeFormatter time = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
    LocalDateTime now = LocalDateTime.now();
    /**
     * Creates new form Usuario2Screen
     */
    public Usuario2Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgBox = new javax.swing.JPanel();
        tituloTxt = new javax.swing.JLabel();
        problem_extratoBox = new javax.swing.JPanel();
        problem_extratoTxt = new javax.swing.JLabel();
        selecioneTxt = new javax.swing.JLabel();
        problem_depositoBox = new javax.swing.JPanel();
        problem_depositoTxt = new javax.swing.JLabel();
        problem_user_textBox = new javax.swing.JPanel();
        problem_user_textTxt = new javax.swing.JLabel();
        popupBox = new javax.swing.JPanel();
        titulo2Txt = new javax.swing.JLabel();
        xbttn = new javax.swing.JLabel();
        user_textTxtF = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        sendBttn = new javax.swing.JButton();
        footerBox = new javax.swing.JPanel();
        squareTxt = new javax.swing.JLabel();
        ballTxt = new javax.swing.JLabel();
        backTxt = new javax.swing.JLabel();
        statusTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        BgBox.setBackground(new java.awt.Color(0, 0, 0));
        BgBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tituloTxt.setText("No que podemos ajudar?");
        BgBox.add(tituloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        problem_extratoBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        problem_extratoBox.setOpaque(false);
        problem_extratoBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                problem_extratoBoxMouseClicked(evt);
            }
        });

        problem_extratoTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        problem_extratoTxt.setText("Não consigo extrair dinheiro");

        javax.swing.GroupLayout problem_extratoBoxLayout = new javax.swing.GroupLayout(problem_extratoBox);
        problem_extratoBox.setLayout(problem_extratoBoxLayout);
        problem_extratoBoxLayout.setHorizontalGroup(
            problem_extratoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(problem_extratoBoxLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(problem_extratoTxt)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        problem_extratoBoxLayout.setVerticalGroup(
            problem_extratoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(problem_extratoBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(problem_extratoTxt)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        BgBox.add(problem_extratoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 360, 50));

        selecioneTxt.setText("Selecione aquilo que melhor se encaixa com seu problema");
        BgBox.add(selecioneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        problem_depositoBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        problem_depositoBox.setOpaque(false);
        problem_depositoBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                problem_depositoBoxMouseClicked(evt);
            }
        });

        problem_depositoTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        problem_depositoTxt.setText("Não consigo depositar dinheiro");

        javax.swing.GroupLayout problem_depositoBoxLayout = new javax.swing.GroupLayout(problem_depositoBox);
        problem_depositoBox.setLayout(problem_depositoBoxLayout);
        problem_depositoBoxLayout.setHorizontalGroup(
            problem_depositoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, problem_depositoBoxLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(problem_depositoTxt)
                .addGap(41, 41, 41))
        );
        problem_depositoBoxLayout.setVerticalGroup(
            problem_depositoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(problem_depositoBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(problem_depositoTxt)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        BgBox.add(problem_depositoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 360, 50));

        problem_user_textBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        problem_user_textBox.setOpaque(false);
        problem_user_textBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                problem_user_textBoxMouseClicked(evt);
            }
        });

        problem_user_textTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        problem_user_textTxt.setText("Outro");

        javax.swing.GroupLayout problem_user_textBoxLayout = new javax.swing.GroupLayout(problem_user_textBox);
        problem_user_textBox.setLayout(problem_user_textBoxLayout);
        problem_user_textBoxLayout.setHorizontalGroup(
            problem_user_textBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(problem_user_textBoxLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(problem_user_textTxt)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        problem_user_textBoxLayout.setVerticalGroup(
            problem_user_textBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(problem_user_textBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(problem_user_textTxt)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        BgBox.add(problem_user_textBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 360, 50));

        popupBox.setOpaque(false);
        popupBox.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo2Txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo2Txt.setText("Conte-nos sobre seu problema");
        popupBox.add(titulo2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        xbttn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        xbttn.setText("X");
        xbttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xbttnMouseClicked(evt);
            }
        });
        popupBox.add(xbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        user_textTxtF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));

        text.setBackground(new java.awt.Color(20, 20, 20));
        text.setColumns(20);
        text.setRows(5);
        user_textTxtF.setViewportView(text);

        popupBox.add(user_textTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 330, 240));

        sendBttn.setBackground(new java.awt.Color(30, 30, 30));
        sendBttn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sendBttn.setForeground(new java.awt.Color(255, 255, 0));
        sendBttn.setText("Enviar");
        sendBttn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 35, 26)));
        sendBttn.setOpaque(true);
        sendBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendBttnMouseClicked(evt);
            }
        });
        popupBox.add(sendBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 100, 30));

        BgBox.add(popupBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 450));

        footerBox.setOpaque(false);

        squareTxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        squareTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        squareTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/squareBttn.png"))); // NOI18N

        ballTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ballTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/circleBttn.png"))); // NOI18N

        backTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/backBttn.png"))); // NOI18N
        backTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout footerBoxLayout = new javax.swing.GroupLayout(footerBox);
        footerBox.setLayout(footerBoxLayout);
        footerBoxLayout.setHorizontalGroup(
            footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerBoxLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(squareTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ballTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backTxt)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        footerBoxLayout.setVerticalGroup(
            footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerBoxLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(squareTxt)
                    .addGroup(footerBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ballTxt)
                        .addComponent(backTxt)))
                .addContainerGap())
        );

        BgBox.add(footerBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 370, 50));
        BgBox.add(statusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        getContentPane().add(BgBox);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void problem_extratoBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_problem_extratoBoxMouseClicked
        String data= time.format(now);
        inset.insertSQLProtocolo("extrato", data);
        statusTxt.setText("Enviado!");
    }//GEN-LAST:event_problem_extratoBoxMouseClicked

    private void problem_depositoBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_problem_depositoBoxMouseClicked
        String data= time.format(now);
        inset.insertSQLProtocolo("deposito", data);
        statusTxt.setText("Enviado!");
    }//GEN-LAST:event_problem_depositoBoxMouseClicked

    private void problem_user_textBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_problem_user_textBoxMouseClicked
        selecioneTxt.setVisible(false);
        tituloTxt.setVisible(false);
        footerBox.setVisible(false);
        problem_extratoBox.setVisible(false);
        problem_depositoBox.setVisible(false);
        problem_user_textBox.setVisible(false);
        statusTxt.setVisible(false);
        popupBox.setVisible(true);
    }//GEN-LAST:event_problem_user_textBoxMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Color bgColor = new Color(20,20,20);
        popupBox.setVisible(false);
        problem_depositoTxt.setForeground(Color.white);
        problem_extratoTxt.setForeground(Color.white);
        problem_user_textTxt.setForeground(Color.white);
        selecioneTxt.setForeground(Color.white);
        titulo2Txt.setForeground(Color.white);
        tituloTxt.setForeground(Color.white);
        user_textTxtF.setForeground(Color.white);
        text.setBackground(Color.getColor("bg", bgColor));
        text.setForeground(Color.white);
        xbttn.setForeground(Color.white);
        statusTxt.setForeground(Color.white);
        statusTxt.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void xbttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xbttnMouseClicked
        popupBox.setVisible(false);
        selecioneTxt.setVisible(true);
        tituloTxt.setVisible(true);
        footerBox.setVisible(true);
        problem_extratoBox.setVisible(true);
        problem_depositoBox.setVisible(true);
        problem_user_textBox.setVisible(true);
        statusTxt.setVisible(true);
    }//GEN-LAST:event_xbttnMouseClicked

    private void backTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTxtMouseClicked
        UsuarioScreen user = new UsuarioScreen();
        this.setVisible(false);
        user.setVisible(true);
    }//GEN-LAST:event_backTxtMouseClicked

    private void sendBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendBttnMouseClicked
        String data = time.format(now);
        inset.insertSQLHistorico(text.getText(), "outro", data);
        
        popupBox.setVisible(false);
        selecioneTxt.setVisible(true);
        tituloTxt.setVisible(true);
        footerBox.setVisible(true);
        problem_extratoBox.setVisible(true);
        problem_depositoBox.setVisible(true);
        problem_user_textBox.setVisible(true);
        statusTxt.setText("Enviado!");
        statusTxt.setVisible(true);
    }//GEN-LAST:event_sendBttnMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario2Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario2Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario2Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario2Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario2Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgBox;
    private javax.swing.JLabel backTxt;
    private javax.swing.JLabel ballTxt;
    private javax.swing.JPanel footerBox;
    private javax.swing.JPanel popupBox;
    private javax.swing.JPanel problem_depositoBox;
    private javax.swing.JLabel problem_depositoTxt;
    private javax.swing.JPanel problem_extratoBox;
    private javax.swing.JLabel problem_extratoTxt;
    private javax.swing.JPanel problem_user_textBox;
    private javax.swing.JLabel problem_user_textTxt;
    private javax.swing.JLabel selecioneTxt;
    private javax.swing.JButton sendBttn;
    private javax.swing.JLabel squareTxt;
    private javax.swing.JLabel statusTxt;
    private javax.swing.JTextArea text;
    private javax.swing.JLabel titulo2Txt;
    private javax.swing.JLabel tituloTxt;
    private javax.swing.JScrollPane user_textTxtF;
    private javax.swing.JLabel xbttn;
    // End of variables declaration//GEN-END:variables
}
